from datasets.models import Video


def get_rotation_options():
    ROTATION_90_DEGREES_CLOCKWISE = Video.VIDEO_ROTATION[0][1]
    ROTATION_180_DEGREES_CLOCKWISE = Video.VIDEO_ROTATION[1][1]
    ROTATION_270_DEGREES_CLOCKWISE = Video.VIDEO_ROTATION[2][1]

    return ROTATION_90_DEGREES_CLOCKWISE, ROTATION_180_DEGREES_CLOCKWISE, ROTATION_270_DEGREES_CLOCKWISE
